name: Draw ZMK keymaps
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build ZMK firmware"]
    types:
      - completed

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap-drawer/config.yaml"
      output_folder: "keymap-drawer-output"
      commit_message: "[Draw] ${{ github.event.workflow_run.head_commit.message || github.event.head_commit.message }}"
